version: '3.4'

services:
  database:
    image: "mysql:8.0.28"
    container_name: Comment-Database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - '../___data___/comment/database:/var/lib/mysql'
    ports:
      - 33060:3306
    env_file:
      - .env
    networks:
      - comment

networks:
  comment:
    driver: bridge
