version: '3.4'

services:
  database:
    image: "mysql:8.0.28"
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: ""        # WILL BE UPDATED
      MYSQL_ROOT_PASSWORD: ""   # WILL BE UPDATED
    networks:
      - comment

networks:
  comment:
    driver: bridge
